### ISSUE TITLE
import ole --> ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by daewonyoon** [hallazzang/ole-py#1]
windows 10, python 3.6 64bit

pip install ole-py 로 설치

```
(olepytest3664) D:\PythonEnvs>pip install ole-py
Collecting ole-py
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/48/60/509a0d3979d5d53024ca05c5ca14bf0c440d14c063f5ec9d047280c7868f/ole_py-0.0.1-py3-none-any.whl
Installing collected packages: ole-py
Successfully installed ole-py-0.0.1
```

import ole 하면 ole.py 안의 import utils 에서 에러가 발생함.
```
(olepytest3664) D:\PythonEnvs>python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ole
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\PythonEnvs\olepytest3664\lib\site-packages\ole.py", line 3, in <module>
    from utils import *
ModuleNotFoundError: No module named 'utils'
```

lib\site-packages 폴더에 보면, `ole.py` 파일은 존재하지만, `utils.py` 파일이 없음.

```
 D:\PythonEnvs\olepytest3664\Lib\site-packages 디렉터리

2018-09-05  오후 10:47    <DIR>          .
2018-09-05  오후 10:47    <DIR>          ..
2018-09-05  오후 10:41               126 easy_install.py
2018-09-05  오후 10:45             9,655 ole.py
2018-09-05  오후 10:47    <DIR>          ole_py-0.0.1-py3.6.egg-info
2018-09-05  오후 10:42    <DIR>          pip
2018-09-05  오후 10:42    <DIR>          pip-9.0.1.dist-info
2018-09-05  오후 10:41    <DIR>          pkg_resources
2018-09-05  오후 10:41    <DIR>          setuptools
2018-09-05  오후 10:41    <DIR>          setuptools-28.8.0.dist-info
```

현재의 github 레포를 clone 하여 pip install . 해도 동일함.

**Comment by hallazzang** [comment]
현재 군 복무 중인 관계로 바로 해당 문제 수정이 힘들 것 같습니다. setup.py의 setup 함수에서 utils.py 모듈도 포함하도록 수정하면 될 것 같습니다.
